## 4.8 Grouping Data & Aggregation Variables

### This notebook contains the following points:

## 1.0 Preparational Steps
## 2.0 Working along the Course Material

## 1.0 Preparational Steps

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
path = r'C:\Users\chris\OneDrive\Desktop\Data Analytics CF\202203_Instacart Basket Analysis'

In [3]:
ords_prods_merged = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merged_new_variables.pkl'))

In [4]:
df = ords_prods_merged[:1000000]

In [5]:
df.shape

(1000000, 19)

In [6]:
df.head(10)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,True,196,1,0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,regular days,Average orders
1,2539329,1,1,2,8,NaN,True,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy,regular days,Average orders
2,2539329,1,1,2,8,NaN,True,12427,3,0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,regular days,Average orders
3,2539329,1,1,2,8,NaN,True,26088,4,0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,regular days,Average orders
4,2539329,1,1,2,8,NaN,True,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy,regular days,Average orders
5,2398795,1,2,3,7,15.0,False,196,1,1,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,slowest days,Average orders
6,2398795,1,2,3,7,15.0,False,10258,2,0,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,slowest days,Average orders
7,2398795,1,2,3,7,15.0,False,12427,3,1,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,slowest days,Average orders
8,2398795,1,2,3,7,15.0,False,13176,4,0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Regularly busy,slowest days,Average orders
9,2398795,1,2,3,7,15.0,False,26088,5,1,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,slowest days,Average orders

## 2.0 Working along the Course Material

### 2.1 Grouping Data with pandas

In [7]:
# grouping df by product_name
df.groupby('product_name')

### 2.2 Performing a Single Aggregation

In [8]:
df.groupby('department_id').agg({'order_number' : ['mean']})

              order_number
                      mean
department_id
1.0              14.800024
2.0              17.091743
3.0              17.913544
4.0              17.893092
5.0              15.214270
6.0              15.382135
7.0              17.694027
8.0              16.458105
9.0              15.957363
10.0             20.091818
11.0             16.482026
12.0             15.615061
13.0             16.484023
14.0             17.524632
15.0             15.691875
16.0             18.014071
17.0             16.150593
18.0             19.602850
19.0             17.631340
20.0             17.138607
21.0             21.956893

In [9]:
df.groupby('department_id')['order_number'].mean()

department_id
1.0     14.800024
2.0     17.091743
3.0     17.913544
4.0     17.893092
5.0     15.214270
6.0     15.382135
7.0     17.694027
8.0     16.458105
9.0     15.957363
10.0    20.091818
11.0    16.482026
12.0    15.615061
13.0    16.484023
14.0    17.524632
15.0    15.691875
16.0    18.014071
17.0    16.150593
18.0    19.602850
19.0    17.631340
20.0    17.138607
21.0    21.956893
Name: order_number, dtype: float64

In [11]:
df.groupby('department_id').order_number.mean()

department_id
1.0     14.800024
2.0     17.091743
3.0     17.913544
4.0     17.893092
5.0     15.214270
6.0     15.382135
7.0     17.694027
8.0     16.458105
9.0     15.957363
10.0    20.091818
11.0    16.482026
12.0    15.615061
13.0    16.484023
14.0    17.524632
15.0    15.691875
16.0    18.014071
17.0    16.150593
18.0    19.602850
19.0    17.631340
20.0    17.138607
21.0    21.956893
Name: order_number, dtype: float64

### 2.3 Performing Multiple Aggregations

In [13]:
df.groupby('department_id').agg({'order_number' : ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1.0              14.800024   1  99
2.0              17.091743   1  98
3.0              17.913544   1  99
4.0              17.893092   1  99
5.0              15.214270   1  99
6.0              15.382135   1  99
7.0              17.694027   1  99
8.0              16.458105   1  91
9.0              15.957363   1  99
10.0             20.091818   1  99
11.0             16.482026   1  99
12.0             15.615061   1  99
13.0             16.484023   1  99
14.0             17.524632   1  99
15.0             15.691875   1  99
16.0             18.014071   1  99
17.0             16.150593   1  99
18.0             19.602850   1  99
19.0             17.631340   1  99
20.0             17.138607   1  99
21.0             21.956893   1  97

### 2.4 Aggregating Data with transform()

In [16]:
ords_prods_merged['max_order'] = ords_prods_merged.groupby(['user_id'])['order_number'].transform(np.max)

In [17]:
ords_prods_merged.head(15)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,True,196,1,0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,regular days,Average orders,10
1,2539329,1,1,2,8,NaN,True,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy,regular days,Average orders,10
2,2539329,1,1,2,8,NaN,True,12427,3,0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,regular days,Average orders,10
3,2539329,1,1,2,8,NaN,True,26088,4,0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,regular days,Average orders,10
4,2539329,1,1,2,8,NaN,True,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy,regular days,Average orders,10
5,2398795,1,2,3,7,15.0,False,196,1,1,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,slowest days,Average orders,10
6,2398795,1,2,3,7,15.0,False,10258,2,0,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,slowest days,Average orders,10
7,2398795,1,2,3,7,15.0,False,12427,3,1,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,slowest days,Average orders,10
8,2398795,1,2,3,7,15.0,False,13176,4,0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Regularly busy,slowest days,Average orders,10
9,2398795,1,2,3,7,15.0,False,26088,5,1,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,slowest days,Average orders,10
10,2398795,1,2,3,7,15.0,False,13032,6,0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Low-range product,Regularly busy,slowest days,Average orders,10
11,473747,1,3,3,12,21.0,False,196,1,1,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,slowest days,Most orders,10
12,473747,1,3,3,12,21.0,False,12427,2,1,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,slowest days,Most orders,10
13,473747,1,3,3,12,21.0,False,10258,3,1,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,slowest days,Most orders,10
14,473747,1,3,3,12,21.0,False,25133,4,0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,slowest days,Most orders,10

In [18]:
pd.options.display.max_rows = None

In [21]:
ords_prods_merged.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,True,196,1,0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,regular days,Average orders,10
1,2539329,1,1,2,8,NaN,True,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy,regular days,Average orders,10
2,2539329,1,1,2,8,NaN,True,12427,3,0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,regular days,Average orders,10
3,2539329,1,1,2,8,NaN,True,26088,4,0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,regular days,Average orders,10
4,2539329,1,1,2,8,NaN,True,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy,regular days,Average orders,10
5,2398795,1,2,3,7,15.0,False,196,1,1,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,slowest days,Average orders,10
6,2398795,1,2,3,7,15.0,False,10258,2,0,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,slowest days,Average orders,10
7,2398795,1,2,3,7,15.0,False,12427,3,1,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,slowest days,Average orders,10
8,2398795,1,2,3,7,15.0,False,13176,4,0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Regularly busy,slowest days,Average orders,10
9,2398795,1,2,3,7,15.0,False,26088,5,1,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,slowest days,Average orders,10
10,2398795,1,2,3,7,15.0,False,13032,6,0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Low-range product,Regularly busy,slowest days,Average orders,10
11,473747,1,3,3,12,21.0,False,196,1,1,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,slowest days,Most orders,10
12,473747,1,3,3,12,21.0,False,12427,2,1,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,slowest days,Most orders,10
13,473747,1,3,3,12,21.0,False,10258,3,1,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,slowest days,Most orders,10
14,473747,1,3,3,12,21.0,False,25133,4,0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,slowest days,Most orders,10
15,473747,1,3,3,12,21.0,False,30450,5,0,Creamy Almond Butter,88.0,13.0,3.2,both,Low-range product,Regularly busy,slowest days,Most orders,10
16,2254736,1,4,4,7,29.0,False,196,1,1,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,slowest days,Average orders,10
17,2254736,1,4,4,7,29.0,False,12427,2,1,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,slowest days,Average orders,10
18,2254736,1,4,4,7,29.0,False,10258,3,1,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,slowest days,Average orders,10
19,2254736,1,4,4,7,29.0,False,25133,4,1,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,slowest days,Average orders,10
20,2254736,1,4,4,7,29.0,False,26405,5,1,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Least busy,slowest days,Average orders,10
21,431534,1,5,4,15,28.0,False,196,1,1,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,slowest days,Most orders,10
22,431534,1,5,4,15,28.0,False,12427,2,1,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,slowest days,Most orders,10
23,431534,1,5,4,15,28.0,False,10258,3,1,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,slowest days,Most orders,10
24,431534,1,5,4,15,28.0,False,25133,4,1,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,slowest days,Most orders,10
25,431534,1,5,4,15,28.0,False,10326,5,0,Organic Fuji Apples,24.0,4.0,2.7,both,Low-range product,Least busy,slowest days,Most orders,10
26,431534,1,5,4,15,28.0,False,17122,6,0,Honeycrisp Apples,24.0,4.0,14.0,both,Mid-range product,Least busy,slowest days,Most orders,10
27,431534,1,5,4,15,28.0,False,41787,7,0,Bartlett Pears,24.0,4.0,5.0,both,Low-range product,Least busy,slowest days,Most orders,10
28,431534,1,5,4,15,28.0,False,13176,8,1,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Least busy,slowest days,Most orders,10
29,3367565,1,6,2,7,19.0,False,196,1,1,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,regular days,Average orders,10
30,3367565,1,6,2,7,19.0,False,12427,2,1,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,regular days,Average orders,10
31,3367565,1,6,2,7,19.0,False,10258,3,1,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,regular days,Average orders,10
32,3367565,1,6,2,7,19.0,False,25133,4,1,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,regular days,Average orders,10
33,550135,1,7,1,9,20.0,False,196,1,1,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,busiest days,Most orders,10
34,550135,1,7,1,9,20.0,False,10258,2,1,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,busiest days,Most orders,10
35,550135,1,7,1,9,20.0,False,12427,3,1,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,busiest days,Most orders,10
36,550135,1,7,1,9,20.0,False,25133,4,1,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,busiest days,Most orders,10
37,550135,1,7,1,9,20.0,False,13032,5,1,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Low-range product,Regularly busy,busiest days,Most orders,10
38,3108588,1,8,1,14,14.0,False,12427,1,1,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,busiest days,Most orders,10
39,3108588,1,8,1,14,14.0,False,196,2,1,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,busiest days,Most orders,10
40,3108588,1,8,1,14,14.0,False,10258,3,1,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,busiest days,Most orders,10
41,3108588,1,8,1,14,14.0,False,25133,4,1,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,busiest days,Most orders,10
42,3108588,1,8,1,14,14.0,False,46149,5,0,Zero Calorie Cola,77.0,7.0,13.4,both,Mid-range product,Regularly busy,busiest days,Most orders,10
43,3108588,1,8,1,14,14.0,False,49235,6,0,Organic Half & Half,53.0,16.0,1.8,both,Low-range product,Regularly busy,busiest days,Most orders,10
44,2295261,1,9,1,16,0.0,False,49235,1,1,Organic Half & Half,53.0,16.0,1.8,both,Low-range product,Regularly busy,busiest days,Most orders,10
45,2295261,1,9,1,16,0.0,False,46149,2,1,Zero Calorie Cola,77.0,7.0,13.4,both,Mid-range product,Regularly busy,busiest days,Most orders,10
46,2295261,1,9,1,16,0.0,False,25133,3,1,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,busiest days,Most orders,10
47,2295261,1,9,1,16,0.0,False,196,4,1,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,busiest days,Most orders,10
48,2295261,1,9,1,16,0.0,False,10258,5,1,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,busiest days,Most orders,10
49,2295261,1,9,1,16,0.0,False,12427,6,1,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,busiest days,Most orders,10
50,2550362,1,10,4,8,30.0,False,196,1,1,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,slowest days,Average orders,10
51,2550362,1,10,4,8,30.0,False,46149,2,1,Zero Calorie Cola,77.0,7.0,13.4,both,Mid-range product,Least busy,slowest days,Average orders,10
52,2550362,1,10,4,8,30.0,False,39657,3,0,Milk Chocolate Almonds,45.0,19.0,6.8,both,Mid-range product,Least busy,slowest days,Average orders,10
53,2550362,1,10,4,8,30.0,False,38928,4,0,0% Greek Strained Yogurt,120.0,16.0,12.6,both,Mid-range product,Least busy,slowest days,Average orders,10
54,2550362,1,10,4,8,30.0,False,25133,5,1,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,slowest days,Average orders,10
55,2550362,1,10,4,8,30.0,False,10258,6,1,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,slowest days,Average orders,10
56,2550362,1,10,4,8,30.0,False,35951,7,0,Organic Unsweetened Almond Milk,91.0,16.0,1.3,both,Low-range product,Least busy,slowest days,Average orders,10
57,2550362,1,10,4,8,30.0,False,13032,8,1,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Low-range product,Least busy,slowest days,Average orders,10
58,2550362,1,10,4,8,30.0,False,12427,9,1,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,slowest days,Average orders,10
59,2168274,2,1,2,11,NaN,True,32792,1,0,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Mid-range product,Regularly busy,regular days,Most orders,14
60,2168274,2,1,2,11,NaN,True,47766,2,0,Organic Avocado,24.0,4.0,6.3,both,Mid-range product,Regularly busy,regular days,Most orders,14
61,2168274,2,1,2,11,NaN,True,20574,3,0,Roasted Turkey,96.0,20.0,2.3,both,Low-range product,Regularly busy,regular days,Most orders,14
62,2168274,2,1,2,11,NaN,True,12000,4,0,Baked Organic Sea Salt Crunchy Pea Snack,72.0,13.0,10.9,both,Mid-range product,Regularly busy,regular days,Most orders,14
63,2168274,2,1,2,11,NaN,True,48110,5,0,Thin Stackers Brown Rice Lightly Salted,78.0,19.0,2.7,both,Low-range product,Regularly busy,regular days,Most orders,14
64,2168274,2,1,2,11,NaN,True,22474,6,0,Cheddar Bunnies Snack Crackers,78.0,19.0,4.1,both,Low-range product,Regularly busy,regular days,Most orders,14
65,2168274,2,1,2,11,NaN,True,16589,7,0,Plantain Chips,107.0,19.0,5.0,both,Low-range product,Regularly busy,regular days,Most orders,14
66,2168274,2,1,2,11,NaN,True,35917,8,0,Organic Just Concord Grape Juice,98.0,7.0,9.4,both,Mid-range product,Regularly busy,regular days,Most orders,14
67,2168274,2,1,2,11,NaN,True,27344,9,0,Uncured Genoa Salami,96.0,20.0,14.8,both,Mid-range product,Regularly busy,regular days,Most orders,14
68,2168274,2,1,2,11,NaN,True,30489,10,0,Original Hummus,67.0,20.0,7.5,both,Mid-range product,Regularly busy,regular days,Most orders,14
69,2168274,2,1,2,11,NaN,True,27966,11,0,Organic Raspberries,123.0,4.0,4.4,both,Low-range product,Regularly busy,regular days,Most orders,14
70,2168274,2,1,2,11,NaN,True,13176,12,0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Regularly busy,regular days,Most orders,14
71,2168274,2,1,2,11,NaN,True,45066,13,0,Honeycrisp Apple,24.0,4.0,2.5,both,Low-range product,Regularly busy,regular days,Most orders,14
72,1501582,2,2,5,10,10.0,False,16797,1,0,Strawberries,24.0,4.0,1.3,both,Low-range product,Regularly busy,regular days,Most orders,14
73,1501582,2,2,5,10,10.0,False,47526,2,0,Goat Cheese Log,21.0,16.0,2.0,both,Low-range product,Regularly busy,regular days,Most orders,14
74,1501582,2,2,5,10,10.0,False,8479,3,0,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Regularly busy,regular days,Most orders,14
75,1501582,2,2,5,10,10.0,False,47766,4,1,Organic Avocado,24.0,4.0,6.3,both,Mid-range product,Regularly busy,regular days,Most orders,14
76,1501582,2,2,5,10,10.0,False,19051,5,0,"Pita Chips, Simply Naked, Party Size",107.0,19.0,3.9,both,Low-range product,Regularly busy,regular days,Most orders,14
77,1501582,2,2,5,10,10.0,False,8138,6,0,Traditional Hummus,67.0,20.0,2.0,both,Low-range product,Regularly busy,regular days,Most orders,14
78,1901567,2,3,1,10,3.0,False,47766,1,1,Organic Avocado,24.0,4.0,6.3,both,Mid-range product,Regularly busy,busiest days,Most orders,14
79,1901567,2,3,1,10,3.0,False,32792,2,1,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Mid-range product,Regularly busy,busiest days,Most orders,14
80,1901567,2,3,1,10,3.0,False,20574,3,1,Roasted Turkey,96.0,20.0,2.3,both,Low-range product,Regularly busy,busiest days,Most orders,14
81,1901567,2,3,1,10,3.0,False,7781,4,0,Organic Sticks Low Moisture Part Skim Mozzarel...,21.0,16.0,6.6,both,Mid-range product,Regularly busy,busiest days,Most orders,14
82,1901567,2,3,1,10,3.0,False,28874,5,0,Carrot Ginger Soup,1.0,20.0,6.2,both,Mid-range product,Regularly busy,busiest days,Most orders,14
83,738281,2,4,2,10,8.0,False,49451,1,0,Artichoke Spinach Dip,67.0,20.0,7.1,both,Mid-range product,Regularly busy,regular days,Most orders,14
84,738281,2,4,2,10,8.0,False,32792,2,1,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Mid-range product,Regularly busy,regular days,Most orders,14
85,738281,2,4,2,10,8.0,False,32139,3,0,Hommus Classic Original,67.0,20.0,7.5,both,Mid-range product,Regularly busy,regular days,Most orders,14
86,738281,2,4,2,10,8.0,False,34688,4,0,Good Belly Probiotics Juice Drink Blueberry Ac...,31.0,7.0,5.8,both,Mid-range product,Regularly busy,regular days,Most orders,14
87,738281,2,4,2,10,8.0,False,36735,5,0,Organic Roasted Sliced Chicken Breast,96.0,20.0,8.9,both,Mid-range product,Regularly busy,regular days,Most orders,14
88,738281,2,4,2,10,8.0,False,37646,6,0,Organic Gala Apples,24.0,4.0,9.1,both,Mid-range product,Regularly busy,regular days,Most orders,14
89,738281,2,4,2,10,8.0,False,22829,7,0,Multigrain Flax Seeded Flatbread Crackers,78.0,19.0,5.5,both,Mid-range product,Regularly busy,regular days,Most orders,14
90,738281,2,4,2,10,8.0,False,24852,8,0,Banana,24.0,4.0,12.3,both,Mid-range product,Regularly busy,regular days,Most orders,14
91,738281,2,4,2,10,8.0,False,47209,9,0,Organic Hass Avocado,24.0,4.0,4.0,both,Low-range product,Regularly busy,regular days,Most orders,14
92,738281,2,4,2,10,8.0,False,33276,10,0,Kalamata Olive Spread,67.0,20.0,10.8,both,Mid-range product,Regularly busy,regular days,Most orders,14
93,738281,2,4,2,10,8.0,False,45613,11,0,Pad Thai,38.0,1.0,12.6,both,Mid-range product,Regularly busy,regular days,Most orders,14
94,738281,2,4,2,10,8.0,False,9681,12,0,Chicken Tikka Masala with Cumin Infused Basmat...,38.0,1.0,2.0,both,Low-range product,Regularly busy,regular days,Most orders,14
95,738281,2,4,2,10,8.0,False,21150,13,0,Fire Grilled Steak Bowl,38.0,1.0,5.9,both,Mid-range product,Regularly busy,regular days,Most orders,14
96,1673511,2,5,3,11,8.0,False,47144,1,0,Unsweetened Original Almond Breeze Almond Milk,91.0,16.0,14.0,both,Mid-range product,Regularly busy,slowest days,Most orders,14
97,1673511,2,5,3,11,8.0,False,5322,2,0,Gluten Free Dark Chocolate Chunk Chewy with a ...,3.0,19.0,2.9,both,Low-range product,Regularly busy,slowest days,Most orders,14
98,1673511,2,5,3,11,8.0,False,17224,3,0,Oats & Honey Gluten Free Granola,3.0,19.0,1.6,both,Low-range product,Regularly busy,slowest days,Most orders,14
99,1673511,2,5,3,11,8.0,False,38656,4,0,Gluten Free Peanut Butter Dark Chocolate Chewy...,3.0,19.0,3.4,both,Low-range product,Regularly busy,slowest days,Most orders,14

### 2.5 Deriving new columns with loc()

In [26]:
ords_prods_merged.loc[ords_prods_merged['max_order'] > 40, 'loyalty_flag']  = 'Loyal customer'

In [27]:
ords_prods_merged.loc[(ords_prods_merged['max_order'] <= 40) & (ords_prods_merged['max_order'] >10), 'loyalty_flag'] = 'Regular customer'

In [28]:
ords_prods_merged.loc[ords_prods_merged['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [29]:
ords_prods_merged.head(20)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag
0,2539329,1,1,2,8,NaN,True,196,1,0,...,77.0,7.0,9.0,both,Mid-range product,Regularly busy,regular days,Average orders,10,New customer
1,2539329,1,1,2,8,NaN,True,14084,2,0,...,91.0,16.0,12.5,both,Mid-range product,Regularly busy,regular days,Average orders,10,New customer
2,2539329,1,1,2,8,NaN,True,12427,3,0,...,23.0,19.0,4.4,both,Low-range product,Regularly busy,regular days,Average orders,10,New customer
3,2539329,1,1,2,8,NaN,True,26088,4,0,...,23.0,19.0,4.7,both,Low-range product,Regularly busy,regular days,Average orders,10,New customer
4,2539329,1,1,2,8,NaN,True,26405,5,0,...,54.0,17.0,1.0,both,Low-range product,Regularly busy,regular days,Average orders,10,New customer
5,2398795,1,2,3,7,15.0,False,196,1,1,...,77.0,7.0,9.0,both,Mid-range product,Regularly busy,slowest days,Average orders,10,New customer
6,2398795,1,2,3,7,15.0,False,10258,2,0,...,117.0,19.0,3.0,both,Low-range product,Regularly busy,slowest days,Average orders,10,New customer
7,2398795,1,2,3,7,15.0,False,12427,3,1,...,23.0,19.0,4.4,both,Low-range product,Regularly busy,slowest days,Average orders,10,New customer
8,2398795,1,2,3,7,15.0,False,13176,4,0,...,24.0,4.0,10.3,both,Mid-range product,Regularly busy,slowest days,Average orders,10,New customer
9,2398795,1,2,3,7,15.0,False,26088,5,1,...,23.0,19.0,4.7,both,Low-range product,Regularly busy,slowest days,Average orders,10,New customer
10,2398795,1,2,3,7,15.0,False,13032,6,0,...,121.0,14.0,4.0,both,Low-range product,Regularly busy,slowest days,Average orders,10,New customer
11,473747,1,3,3,12,21.0,False,196,1,1,...,77.0,7.0,9.0,both,Mid-range product,Regularly busy,slowest days,Most orders,10,New customer
12,473747,1,3,3,12,21.0,False,12427,2,1,...,23.0,19.0,4.4,both,Low-range product,Regularly busy,slowest days,Most orders,10,New customer
13,473747,1,3,3,12,21.0,False,10258,3,1,...,117.0,19.0,3.0,both,Low-range product,Regularly busy,slowest days,Most orders,10,New customer
14,473747,1,3,3,12,21.0,False,25133,4,0,...,21.0,16.0,8.6,both,Mid-range product,Regularly busy,slowest days,Most orders,10,New customer
15,473747,1,3,3,12,21.0,False,30450,5,0,...,88.0,13.0,3.2,both,Low-range product,Regularly busy,slowest days,Most orders,10,New customer
16,2254736,1,4,4,7,29.0,False,196,1,1,...,77.0,7.0,9.0,both,Mid-range product,Least busy,slowest days,Average orders,10,New customer
17,2254736,1,4,4,7,29.0,False,12427,2,1,...,23.0,19.0,4.4,both,Low-range product,Least busy,slowest days,Average orders,10,New customer
18,2254736,1,4,4,7,29.0,False,10258,3,1,...,117.0,19.0,3.0,both,Low-range product,Least busy,slowest days,Average orders,10,New customer
19,2254736,1,4,4,7,29.0,False,25133,4,1,...,21.0,16.0,8.6,both,Mid-range product,Least busy,slowest days,Average orders,10,New customer

In [30]:
ords_prods_merged['loyalty_flag'].value_counts()

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [31]:
ords_prods_merged[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             1
2         1      New customer             1
3         1      New customer             1
4         1      New customer             1
5         1      New customer             2
6         1      New customer             2
7         1      New customer             2
8         1      New customer             2
9         1      New customer             2
10        1      New customer             2
11        1      New customer             3
12        1      New customer             3
13        1      New customer             3
14        1      New customer             3
15        1      New customer             3
16        1      New customer             4
17        1      New customer             4
18        1      New customer             4
19        1      New customer             4
20        1      New customer             4
21        1      New customer             5
22        1      New customer             5
23        1      New customer             5
24        1      New customer             5
25        1      New customer             5
26        1      New customer             5
27        1      New customer             5
28        1      New customer             5
29        1      New customer             6
30        1      New customer             6
31        1      New customer             6
32        1      New customer             6
33        1      New customer             7
34        1      New customer             7
35        1      New customer             7
36        1      New customer             7
37        1      New customer             7
38        1      New customer             8
39        1      New customer             8
40        1      New customer             8
41        1      New customer             8
42        1      New customer             8
43        1      New customer             8
44        1      New customer             9
45        1      New customer             9
46        1      New customer             9
47        1      New customer             9
48        1      New customer             9
49        1      New customer             9
50        1      New customer            10
51        1      New customer            10
52        1      New customer            10
53        1      New customer            10
54        1      New customer            10
55        1      New customer            10
56        1      New customer            10
57        1      New customer            10
58        1      New customer            10
59        2  Regular customer             1